export const cityList = [
    {
        provinsi: "Aceh",
        kota: [
            "Banda Aceh",
            "Langsa",
            "Lhokseumawe",
            "Sabang",
            "Subulussalam",
            "Kabupaten Aceh Barat",
            "Kabupaten Aceh Barat Daya",
            "Kabupaten Aceh Besar",
            "Kabupaten Aceh Jaya",
            "Kabupaten Aceh Selatan",
            "Kabupaten Aceh Singkil",
            "Kabupaten Aceh Tamiang",
            "Kabupaten Aceh Tengah",
            "Kabupaten Aceh Tenggara",
            "Kabupaten Aceh Timur",
            "Kabupaten Aceh Utara",
            "Kabupaten Bener Meriah",
            "Kabupaten Bireuen",
            "Kabupaten Gayo Lues",
            "Kabupaten Nagan Raya",
            "Kabupaten Pidie",
            "Kabupaten Pidie Jaya",
            "Kabupaten Simeulue",
        ],
    },
    {
        provinsi: "Sumatera Utara",
        kota: [
            "Medan",
            "Binjai",
            "Padang Sidempuan",
            "Pematangsiantar",
            "Sibolga",
            "Tanjungbalai",
            "Tebing Tinggi",
            "Gunungsitoli",
            "Kabupaten Asahan",
            "Kabupaten Batu Bara",
            "Kabupaten Dairi",
            "Kabupaten Deli Serdang",
            "Kabupaten Humbang Hasundutan",
            "Kabupaten Karo",
            "Kabupaten Labuhanbatu",
            "Kabupaten Labuhanbatu Selatan",
            "Kabupaten Labuhanbatu Utara",
            "Kabupaten Langkat",
            "Kabupaten Mandailing Natal",
            "Kabupaten Nias",
            "Kabupaten Nias Barat",
            "Kabupaten Nias Selatan",
            "Kabupaten Nias Utara",
            "Kabupaten Padang Lawas",
            "Kabupaten Padang Lawas Utara",
            "Kabupaten Pakpak Bharat",
            "Kabupaten Samosir",
            "Kabupaten Serdang Bedagai",
            "Kabupaten Simalungun",
            "Kabupaten Tapanuli Selatan",
            "Kabupaten Tapanuli Tengah",
            "Kabupaten Tapanuli Utara",
            "Kabupaten Toba",
        ],
    },
    {
        provinsi: "Sumatera Barat",
        kota: [
            "Padang",
            "Bukittinggi",
            "Padangpanjang",
            "Pariaman",
            "Payakumbuh",
            "Sawahlunto",
            "Solok",
            "Kabupaten Agam",
            "Kabupaten Dharmasraya",
            "Kabupaten Kepulauan Mentawai",
            "Kabupaten Lima Puluh Kota",
            "Kabupaten Padang Pariaman",
            "Kabupaten Pasaman",
            "Kabupaten Pasaman Barat",
            "Kabupaten Pesisir Selatan",
            "Kabupaten Sijunjung",
            "Kabupaten Solok",
            "Kabupaten Solok Selatan",
            "Kabupaten Tanah Datar",
        ],
    },
    {
        provinsi: "Riau",
        kota: [
            "Pekanbaru",
            "Dumai",
            "Kabupaten Bengkalis",
            "Kabupaten Indragiri Hilir",
            "Kabupaten Indragiri Hulu",
            "Kabupaten Kampar",
            "Kabupaten Kepulauan Meranti",
            "Kabupaten Kuantan Singingi",
            "Kabupaten Pelalawan",
            "Kabupaten Rokan Hilir",
            "Kabupaten Rokan Hulu",
            "Kabupaten Siak",
        ],
    },
    {
        provinsi: "Kepulauan Riau",
        kota: [
            "Batam",
            "Tanjungpinang",
            "Kabupaten Bintan",
            "Kabupaten Karimun",
            "Kabupaten Kepulauan Anambas",
            "Kabupaten Lingga",
            "Kabupaten Natuna",
        ],
    },
    {
        provinsi: "Jambi",
        kota: [
            "Jambi",
            "Sungai Penuh",
            "Kabupaten Batanghari",
            "Kabupaten Bungo",
            "Kabupaten Kerinci",
            "Kabupaten Merangin",
            "Kabupaten Muaro Jambi",
            "Kabupaten Sarolangun",
            "Kabupaten Tanjung Jabung Barat",
            "Kabupaten Tanjung Jabung Timur",
            "Kabupaten Tebo",
        ],
    },
    {
        provinsi: "Sumatera Selatan",
        kota: [
            "Palembang",
            "Lubuklinggau",
            "Pagar Alam",
            "Prabumulih",
            "Kabupaten Banyuasin",
            "Kabupaten Empat Lawang",
            "Kabupaten Lahat",
            "Kabupaten Muara Enim",
            "Kabupaten Musi Banyuasin",
            "Kabupaten Musi Rawas",
            "Kabupaten Musi Rawas Utara",
            "Kabupaten Ogan Ilir",
            "Kabupaten Ogan Komering Ilir",
            "Kabupaten Ogan Komering Ulu",
            "Kabupaten Ogan Komering Ulu Selatan",
            "Kabupaten Ogan Komering Ulu Timur",
            "Kabupaten Penukal Abab Lematang Ilir",
        ],
    },
    {
        provinsi: "Bangka Belitung",
        kota: [
            "Pangkalpinang",
            "Kabupaten Bangka",
            "Kabupaten Bangka Barat",
            "Kabupaten Bangka Selatan",
            "Kabupaten Bangka Tengah",
            "Kabupaten Belitung",
            "Kabupaten Belitung Timur",
        ],
    },
    {
        provinsi: "Bengkulu",
        kota: [
            "Bengkulu",
            "Kabupaten Bengkulu Selatan",
            "Kabupaten Bengkulu Tengah",
            "Kabupaten Bengkulu Utara",
            "Kabupaten Kaur",
            "Kabupaten Kepahiang",
            "Kabupaten Lebong",
            "Kabupaten Muko Muko",
            "Kabupaten Rejang Lebong",
            "Kabupaten Seluma",
        ],
    },
    {
        provinsi: "Lampung",
        kota: [
            "Bandar Lampung",
            "Metro",
            "Kabupaten Lampung Barat",
            "Kabupaten Lampung Selatan",
            "Kabupaten Lampung Tengah",
            "Kabupaten Lampung Timur",
            "Kabupaten Lampung Utara",
            "Kabupaten Mesuji",
            "Kabupaten Pesawaran",
            "Kabupaten Pesisir Barat",
            "Kabupaten Pringsewu",
            "Kabupaten Tanggamus",
            "Kabupaten Tulang Bawang",
            "Kabupaten Tulang Bawang Barat",
            "Kabupaten Way Kanan",
        ],
    },
    {
        provinsi: "Banten",
        kota: [
            "Serang",
            "Cilegon",
            "Tangerang",
            "Tangerang Selatan",
            "Kabupaten Lebak",
            "Kabupaten Pandeglang",
            "Kabupaten Serang",
            "Kabupaten Tangerang",
        ],
    },
    {
        provinsi: "DKI Jakarta",
        kota: [
            "Jakarta Pusat",
            "Jakarta Utara",
            "Jakarta Barat",
            "Jakarta Timur",
            "Jakarta Selatan",
            "Kepulauan Seribu",
        ],
    },
    {
        provinsi: "Jawa Barat",
        kota: [
            "Bandung",
            "Banjar",
            "Bekasi",
            "Bogor",
            "Cimahi",
            "Cirebon",
            "Depok",
            "Sukabumi",
            "Tasikmalaya",
            "Kabupaten Bandung",
            "Kabupaten Bandung Barat",
            "Kabupaten Bekasi",
            "Kabupaten Bogor",
            "Kabupaten Ciamis",
            "Kabupaten Cianjur",
            "Kabupaten Cirebon",
            "Kabupaten Garut",
            "Kabupaten Indramayu",
            "Kabupaten Karawang",
            "Kabupaten Kuningan",
            "Kabupaten Majalengka",
            "Kabupaten Pangandaran",
            "Kabupaten Purwakarta",
            "Kabupaten Subang",
            "Kabupaten Sukabumi",
            "Kabupaten Sumedang",
            "Kabupaten Tasikmalaya",
        ],
    },
    {
        provinsi: "Jawa Tengah",
        kota: [
            "Magelang",
            "Pekalongan",
            "Salatiga",
            "Semarang",
            "Surakarta",
            "Tegal",
            "Kabupaten Banjarnegara",
            "Kabupaten Banyumas",
            "Kabupaten Batang",
            "Kabupaten Blora",
            "Kabupaten Boyolali",
            "Kabupaten Brebes",
            "Kabupaten Cilacap",
            "Kabupaten Demak",
            "Kabupaten Grobogan",
            "Kabupaten Jepara",
            "Kabupaten Karanganyar",
            "Kabupaten Kebumen",
            "Kabupaten Kendal",
            "Kabupaten Klaten",
            "Kabupaten Kudus",
            "Kabupaten Magelang",
            "Kabupaten Pati",
            "Kabupaten Pekalongan",
            "Kabupaten Pemalang",
            "Kabupaten Purbalingga",
            "Kabupaten Purworejo",
            "Kabupaten Rembang",
            "Kabupaten Semarang",
            "Kabupaten Sragen",
            "Kabupaten Sukoharjo",
            "Kabupaten Tegal",
            "Kabupaten Temanggung",
            "Kabupaten Wonogiri",
            "Kabupaten Wonosobo",
        ],
    },
    {
        provinsi: "DI Yogyakarta",
        kota: [
            "Yogyakarta",
            "Kabupaten Bantul",
            "Kabupaten Gunungkidul",
            "Kabupaten Kulon Progo",
            "Kabupaten Sleman",
        ],
    },
    {
        provinsi: "Jawa Timur",
        kota: [
            "Batu",
            "Blitar",
            "Kediri",
            "Madiun",
            "Malang",
            "Mojokerto",
            "Pasuruan",
            "Probolinggo",
            "Surabaya",
            "Kabupaten Bangkalan",
            "Kabupaten Banyuwangi",
            "Kabupaten Blitar",
            "Kabupaten Bojonegoro",
            "Kabupaten Bondowoso",
            "Kabupaten Gresik",
            "Kabupaten Jember",
            "Kabupaten Jombang",
            "Kabupaten Kediri",
            "Kabupaten Lamongan",
            "Kabupaten Lumajang",
            "Kabupaten Madiun",
            "Kabupaten Magetan",
            "Kabupaten Malang",
            "Kabupaten Mojokerto",
            "Kabupaten Nganjuk",
            "Kabupaten Ngawi",
            "Kabupaten Pacitan",
            "Kabupaten Pamekasan",
            "Kabupaten Pasuruan",
            "Kabupaten Ponorogo",
            "Kabupaten Probolinggo",
            "Kabupaten Sampang",
            "Kabupaten Sidoarjo",
            "Kabupaten Situbondo",
            "Kabupaten Sumenep",
            "Kabupaten Trenggalek",
            "Kabupaten Tuban",
            "Kabupaten Tulungagung",
        ],
    },
    {
        provinsi: "Bali",
        kota: [
            "Denpasar",
            "Kabupaten Badung",
            "Kabupaten Bangli",
            "Kabupaten Buleleng",
            "Kabupaten Gianyar",
            "Kabupaten Jembrana",
            "Kabupaten Karangasem",
            "Kabupaten Klungkung",
            "Kabupaten Tabanan",
        ],
    },
    {
        provinsi: "Nusa Tenggara Barat",
        kota: [
            "Bima",
            "Mataram",
            "Kabupaten Bima",
            "Kabupaten Dompu",
            "Kabupaten Lombok Barat",
            "Kabupaten Lombok Tengah",
            "Kabupaten Lombok Timur",
            "Kabupaten Lombok Utara",
            "Kabupaten Sumbawa",
            "Kabupaten Sumbawa Barat",
        ],
    },
    {
        provinsi: "Nusa Tenggara Timur",
        kota: [
            "Kupang",
            "Kabupaten Alor",
            "Kabupaten Belu",
            "Kabupaten Ende",
            "Kabupaten Flores Timur",
            "Kabupaten Lembata",
            "Kabupaten Malaka",
            "Kabupaten Manggarai",
            "Kabupaten Manggarai Barat",
            "Kabupaten Manggarai Timur",
            "Kabupaten Nagekeo",
            "Kabupaten Ngada",
            "Kabupaten Rote Ndao",
            "Kabupaten Sabu Raijua",
            "Kabupaten Sikka",
            "Kabupaten Sumba Barat",
            "Kabupaten Sumba Barat Daya",
            "Kabupaten Sumba Tengah",
            "Kabupaten Sumba Timur",
            "Kabupaten Timor Tengah Selatan",
            "Kabupaten Timor Tengah Utara",
        ],
    },
    {
        provinsi: "Kalimantan Barat",
        kota: [
            "Pontianak",
            "Singkawang",
            "Kabupaten Bengkayang",
            "Kabupaten Kapuas Hulu",
            "Kabupaten Kayong Utara",
            "Kabupaten Ketapang",
            "Kabupaten Kubu Raya",
            "Kabupaten Landak",
            "Kabupaten Melawi",
            "Kabupaten Mempawah",
            "Kabupaten Sambas",
            "Kabupaten Sanggau",
            "Kabupaten Sekadau",
            "Kabupaten Sintang",
        ],
    },
    {
        provinsi: "Kalimantan Tengah",
        kota: [
            "Palangka Raya",
            "Kabupaten Barito Selatan",
            "Kabupaten Barito Timur",
            "Kabupaten Barito Utara",
            "Kabupaten Gunung Mas",
            "Kabupaten Kapuas",
            "Kabupaten Katingan",
            "Kabupaten Kotawaringin Barat",
            "Kabupaten Kotawaringin Timur",
            "Kabupaten Lamandau",
            "Kabupaten Murung Raya",
            "Kabupaten Pulang Pisau",
            "Kabupaten Seruyan",
            "Kabupaten Sukamara",
        ],
    },
    {
        provinsi: "Kalimantan Selatan",
        kota: [
            "Banjarbaru",
            "Banjarmasin",
            "Kabupaten Balangan",
            "Kabupaten Banjar",
            "Kabupaten Barito Kuala",
            "Kabupaten Hulu Sungai Selatan",
            "Kabupaten Hulu Sungai Tengah",
            "Kabupaten Hulu Sungai Utara",
            "Kabupaten Kotabaru",
            "Kabupaten Tabalong",
            "Kabupaten Tanah Bumbu",
            "Kabupaten Tanah Laut",
            "Kabupaten Tapin",
        ],
    },
    {
        provinsi: "Kalimantan Timur",
        kota: [
            "Balikpapan",
            "Bontang",
            "Samarinda",
            "Kabupaten Berau",
            "Kabupaten Kutai Barat",
            "Kabupaten Kutai Kartanegara",
            "Kabupaten Kutai Timur",
            "Kabupaten Mahakam Ulu",
            "Kabupaten Paser",
            "Kabupaten Penajam Paser Utara",
        ],
    },
    {
        provinsi: "Kalimantan Utara",
        kota: [
            "Tarakan",
            "Kabupaten Bulungan",
            "Kabupaten Malinau",
            "Kabupaten Nunukan",
            "Kabupaten Tana Tidung",
        ],
    },
    {
        provinsi: "Sulawesi Utara",
        kota: [
            "Bitung",
            "Kotamobagu",
            "Manado",
            "Tomohon",
            "Kabupaten Bolaang Mongondow",
            "Kabupaten Bolaang Mongondow Selatan",
            "Kabupaten Bolaang Mongondow Timur",
            "Kabupaten Bolaang Mongondow Utara",
            "Kabupaten Kepulauan Sangihe",
            "Kabupaten Kepulauan Siau Tagulandang Biaro",
            "Kabupaten Kepulauan Talaud",
            "Kabupaten Minahasa",
            "Kabupaten Minahasa Selatan",
            "Kabupaten Minahasa Tenggara",
            "Kabupaten Minahasa Utara",
        ],
    },
    {
        provinsi: "Gorontalo",
        kota: [
            "Gorontalo",
            "Kabupaten Boalemo",
            "Kabupaten Bone Bolango",
            "Kabupaten Gorontalo",
            "Kabupaten Gorontalo Utara",
            "Kabupaten Pohuwato",
        ],
    },
    {
        provinsi: "Sulawesi Tengah",
        kota: [
            "Palu",
            "Kabupaten Banggai",
            "Kabupaten Banggai Kepulauan",
            "Kabupaten Banggai Laut",
            "Kabupaten Buol",
            "Kabupaten Donggala",
            "Kabupaten Morowali",
            "Kabupaten Morowali Utara",
            "Kabupaten Parigi Moutong",
            "Kabupaten Poso",
            "Kabupaten Sigi",
            "Kabupaten Tojo Una-Una",
            "Kabupaten Tolitoli",
        ],
    },
    {
        provinsi: "Sulawesi Barat",
        kota: [
            "Kabupaten Majene",
            "Kabupaten Mamasa",
            "Kabupaten Mamuju",
            "Kabupaten Mamuju Tengah",
            "Kabupaten Pasangkayu",
            "Kabupaten Polewali Mandar",
        ],
    },
    {
        provinsi: "Sulawesi Selatan",
        kota: [
            "Makassar",
            "Palopo",
            "Parepare",
            "Kabupaten Bantaeng",
            "Kabupaten Barru",
            "Kabupaten Bone",
            "Kabupaten Bulukumba",
            "Kabupaten Enrekang",
            "Kabupaten Gowa",
            "Kabupaten Jeneponto",
            "Kabupaten Kepulauan Selayar",
            "Kabupaten Luwu",
            "Kabupaten Luwu Timur",
            "Kabupaten Luwu Utara",
            "Kabupaten Maros",
            "Kabupaten Pangkajene dan Kepulauan",
            "Kabupaten Pinrang",
            "Kabupaten Sidenreng Rappang",
            "Kabupaten Sinjai",
            "Kabupaten Soppeng",
            "Kabupaten Takalar",
            "Kabupaten Tana Toraja",
            "Kabupaten Toraja Utara",
            "Kabupaten Wajo",
        ],
    },
    {
        provinsi: "Sulawesi Tenggara",
        kota: [
            "Bau-Bau",
            "Kendari",
            "Kabupaten Bombana",
            "Kabupaten Buton",
            "Kabupaten Buton Selatan",
            "Kabupaten Buton Tengah",
            "Kabupaten Buton Utara",
            "Kabupaten Kolaka",
            "Kabupaten Kolaka Timur",
            "Kabupaten Kolaka Utara",
            "Kabupaten Konawe",
            "Kabupaten Konawe Kepulauan",
            "Kabupaten Konawe Selatan",
            "Kabupaten Konawe Utara",
            "Kabupaten Muna",
            "Kabupaten Muna Barat",
            "Kabupaten Wakatobi",
        ],
    },
    {
        provinsi: "Maluku",
        kota: [
            "Ambon",
            "Tual",
            "Kabupaten Buru",
            "Kabupaten Buru Selatan",
            "Kabupaten Kepulauan Aru",
            "Kabupaten Kepulauan Tanimbar",
            "Kabupaten Maluku Barat Daya",
            "Kabupaten Maluku Tengah",
            "Kabupaten Maluku Tenggara",
            "Kabupaten Seram Bagian Barat",
            "Kabupaten Seram Bagian Timur",
        ],
    },
    {
        provinsi: "Maluku Utara",
        kota: [
            "Ternate",
            "Tidore Kepulauan",
            "Kabupaten Halmahera Barat",
            "Kabupaten Halmahera Tengah",
            "Kabupaten Halmahera Timur",
            "Kabupaten Halmahera Utara",
            "Kabupaten Halmahera Selatan",
            "Kabupaten Kepulauan Sula",
            "Kabupaten Pulau Morotai",
            "Kabupaten Pulau Taliabu",
        ],
    },
    {
        provinsi: "Papua",
        kota: [
            "Jayapura",
            "Kabupaten Biak Numfor",
            "Kabupaten Jayapura",
            "Kabupaten Jayawijaya",
            "Kabupaten Keerom",
            "Kabupaten Kepulauan Yapen",
            "Kabupaten Mamberamo Raya",
            "Kabupaten Mamberamo Tengah",
            "Kabupaten Membramo Tengah",
            "Kabupaten Pegunungan Bintang",
            "Kabupaten Sarmi",
            "Kabupaten Supiori",
            "Kabupaten Tolikara",
            "Kabupaten Waropen",
            "Kabupaten Yahukimo",
            "Kabupaten Yalimo",
        ],
    },
    {
        provinsi: "Papua Tengah",
        kota: [
            "Kabupaten Deiyai",
            "Kabupaten Dogiyai",
            "Kabupaten Intan Jaya",
            "Kabupaten Mimika",
            "Kabupaten Nabire",
            "Kabupaten Paniai",
        ],
    },
    {
        provinsi: "Papua Pegunungan",
        kota: [
            "Kabupaten Jayawijaya",
            "Kabupaten Lanny Jaya",
            "Kabupaten Mamberamo Tengah",
            "Kabupaten Nduga",
            "Kabupaten Pegunungan Bintang",
            "Kabupaten Tolikara",
            "Kabupaten Yahukimo",
            "Kabupaten Yalimo",
        ],
    },
    {
        provinsi: "Papua Selatan",
        kota: [
            "Kabupaten Asmat",
            "Kabupaten Boven Digoel",
            "Kabupaten Mappi",
            "Kabupaten Merauke",
        ],
    },
    {
        provinsi: "Papua Barat",
        kota: [
            "Sorong",
            "Kabupaten Fakfak",
            "Kabupaten Kaimana",
            "Kabupaten Manokwari",
            "Kabupaten Manokwari Selatan",
            "Kabupaten Maybrat",
            "Kabupaten Pegunungan Arfak",
            "Kabupaten Raja Ampat",
            "Kabupaten Sorong",
            "Kabupaten Sorong Selatan",
            "Kabupaten Tambrauw",
            "Kabupaten Teluk Bintuni",
            "Kabupaten Teluk Wondama",
        ],
    },
    {
        provinsi: "Papua Barat Daya",
        kota: [
            "Sorong",
            "Kabupaten Maybrat",
            "Kabupaten Sorong",
            "Kabupaten Sorong Selatan",
            "Kabupaten Tambrauw",
        ],
    },
];
